<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Pyxl\CheckoutUploadField\Block\Info\Purchaseorder
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <strong><?php echo $block->escapeHtml(__('Purchase Order Number')) ?></strong>
        <span class="number"><?php echo $block->escapeHtml($block->getPoNumber()) ?></span>
        <br />
        <strong><?php echo $block->escapeHtml(__('Purchase Order File')) ?></strong>
        <?php echo $block->getPurchaseorderFileLink() ?: __('N/A') ?>
        <br />
        <strong><?php echo $block->escapeHtml(__('Finance Contact')) ?></strong>
        <span class="number">
            <?php echo $block->escapeHtml($this->getInfo()->getAdditionalInformation('po_contact')) ?: __('N/A') ?>
        </span>
        <br />
    </dd>
</dl>
